import React, { useState } from 'react'
import { journalArticles } from '../data/journal'
import type { JournalArticle } from '../data/journal'
import { JournalCard } from './JournalPage'
import { Arrow } from '../components/UI'

export default function ArticlePage({ article }: { article: JournalArticle }) {
  const [shareStatus, setShareStatus] = useState('')
  const copyLink = async () => { try { await navigator.clipboard.writeText(window.location.href); setShareStatus('Link copied.') } catch { setShareStatus('Copy the page address from your browser to share this story.') } }
  return <div className="journal-article-page"><header className="journal-article-header site-content-width"><a className="journal-article-back" href="/journal"><Arrow left /> THE JOURNAL</a><p className="overline">{article.category} · {article.readTime}</p><h1 tabIndex={-1} data-page-heading>{article.title}</h1><p>{article.summary}</p><div className="journal-article-byline"><span>WYATTEL EDITORIAL · PLANNING GUIDE</span><button className="journal-article-share" onClick={copyLink}>COPY STORY LINK <Arrow /></button></div><p className="journal-share-status" role="status">{shareStatus}</p></header><div className="journal-article-cover"><img src={article.image} alt={article.imageAlt} decoding="async" /></div><div className="journal-article-layout site-content-width"><aside className="journal-article-toc"><p className="overline">IN THIS STORY</p>{article.sections.map((section, index) => <a href={`#article-section-${index}`} key={section.title}>{String(index + 1).padStart(2, '0')} {section.title}</a>)}<a href={article.action.href}>{article.action.label} <Arrow /></a></aside><article className="journal-article-body" data-selectable="true">{article.sections.map((section, index) => <section id={`article-section-${index}`} key={section.title}><h2>{section.title}</h2>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</section>)}<div className="journal-article-note"><p>This is an editorial planning guide, not a guest testimonial or a confirmed hotel package. Ask Wyattel to confirm current arrangements for your visit.</p><a href={article.action.href}>{article.action.label} <Arrow /></a></div></article></div><section className="journal-related site-content-width"><p className="overline">KEEP EXPLORING</p><h2>A little more inspiration.</h2><div className="journal-story-grid">{journalArticles.filter(item => article.related.includes(item.slug)).map(item => <JournalCard key={item.slug} article={item} />)}</div></section></div>
}
