import type { Experience, Room } from './types'
import { suiteGalleries } from './data/suiteGalleries'

export const rooms: Room[] = [
  { name: 'Deluxe Suite', note: 'Comfort for every stay · ₱1,900 / night', image: '/Pictures/Wyattel%20Suite%201%20Background.png', text: 'A polished, comfortable suite with the essentials for an easy overnight stay in Tacurong.', facts: ['₱1,900 / NIGHT', 'AIR-CONDITIONED', 'PRIVATE BATH'] },
  { name: 'Twin Suite', note: 'Accessible comfort · ₱2,400 / night', image: '/Pictures/Wyattel%20Suite%202%20Background.png', text: 'A thoughtful suite for guests who value extra comfort and a stay that feels easy from arrival.', facts: ['₱2,400 / NIGHT', 'ACCESSIBLE', 'PRIVATE BATH'] },
  { name: 'Presidential Suite', note: 'A more spacious stay · ₱2,400 / night', image: '/Pictures/Wyattel%20Suite%201%20Background.png', text: 'A generous room for settling in, with a calm atmosphere for business trips, celebrations and longer visits.', facts: ['₱2,400 / NIGHT', 'SPACIOUS ROOM', 'PRIVATE BATH'] },
  { name: 'Matrimonial Suite', note: 'A private stay for two · ₱2,900 / night', image: '/Pictures/Wyattel%20Suite%202%20Background.png', text: 'A restful suite for two, with a comfortable bed and the quiet ease of a private retreat.', facts: ['₱2,900 / NIGHT', 'QUEEN BED', 'PRIVATE BATH'] },
  { name: 'Family Suite', note: 'Room for everyone · ₱3,400 / night', image: '/Pictures/Wyattel%20Suite%201%20Background.png', text: 'A practical, welcoming choice for family visits, with room to settle in together.', facts: ['₱3,400 / NIGHT', 'FAMILY STAY', 'PRIVATE BATH'] },
].map((room) => ({ ...room, gallery: suiteGalleries[room.name] }))

export const experiences: Experience[] = [
  { id: 'weddings', number: '01', title: 'Say “I Do”', eyebrow: 'To the perfect beginning', text: 'Begin your wedding story at Wyattel Suite. Our elegant wedding room is ideal for preparation and photo-shoot moments—a beautiful setting to create timeless memories in style and comfort.', image: '/Pictures/Wyattel%20Suite%20Wedding.png', imageAlt: 'Wedding couple at Wyattel Suite', position: 'center' },
  { id: 'modern-luxury', number: '02', title: 'Modern Luxury Hotel', eyebrow: 'A refined stay, made for you', text: 'Discover modern luxury at Wyattel Suite, where thoughtfully designed rooms, contemporary comfort and warm hospitality come together. Settle in, slow down and enjoy a stay that feels beautifully personal.', image: '/Pictures/Wyattel%20Suite%201%20Background.png', imageAlt: 'Guest suite at Wyattel Suite', position: 'center' },
  { id: 'events', number: '03', title: 'Every Event, Handled Here', eyebrow: 'Every occasion belongs here', text: 'From birthdays and reunions to meetings and milestone celebrations, make Wyattel Suite part of your occasion. Share your plans with our team and let us help shape an event that feels right for you.', image: '/Pictures/Wyattel%20Hero%20Background.png', imageAlt: 'Wyattel Suite building and entrance in Tacurong City', position: 'center' },
  { id: 'dining', number: '04', title: 'Delicious Dining', eyebrow: 'Be full with our delicious food menu', text: 'Come hungry and leave satisfied. Explore our delicious food menu and enjoy a comforting meal with family, friends or fellow travellers at Wyattel Suite.', image: '/Pictures/Wyattel%20Suite%20Filipino%20Menu.png', imageAlt: 'Wyattel Suite Filipino food menu', position: 'center' },
]
